import Head from "next/head";

/*all css import*/
import "../../styles/main.css";
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from "../components/bootstrapClient";
import AppProvider from "./app-provider";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Không nên dùng next/head trong app directory, nên chuyển qua metadata api*/}
      <Head>
        <title>Petpal</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <link rel="icon" href="assets/images/sm-logo.svg" />
      </Head>
      <body>
        <BootstrapClient />
        <AppProvider>
          {children}
        </AppProvider>

      </body>
      {/* <body className={`${inter.className} antialiased`}>{children}</body> */}
    </html>
  );
}

